variable "region" {}
variable "profile" {}
variable "availability_zone" {}
variable "vpc_name" {}
variable "key_name" {}
variable "provision_key" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "ami_id" {}